source 'http://rubygems.org'

gem 'rails', '3.1.0'
gem 'active_reload', :path => '../../../active_reload'
gem 'sqlite3'

# Asset template engines
#gem 'sass-rails', "~> 3.1.0.rc"
#gem 'coffee-script'
#gem 'uglifier'

gem 'jquery-rails'
